### ISSUE TITLE
Dev branch

### ISSUE THREAD

**Issue by cyborgshead** [cybercongress/cw-cyber#9]
- cw1/cw3 with cyber messages
- dao-dao with cyber messages
- Native and cw20 farms
- IBC-reflect cyber messages
- Boosters
   - neurons
   - cyberlinks
   - particles
- Prediction markets
- AMM for prediction markets
- Bitcoin light client
- Ethereum light client
- PoW GPU token mining
- BLS-12-381 cosmwasm vm native
   - verify
   - verify batch
   - pairing
   - hash to curve
- cw20 with linking
- cw721 with linking
- Progs (DMN)
   - prog with staking and investminting 
   - prog with cyberlinking

**Comment by cyborgshead** [comment]
- ZK-NFT

**Comment by mastercyb** [comment]
closed in favor of standalone issues
